# Generated by Django 4.2.4 on 2023-09-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGaleriaWeb', '0002_artista_alter_obraarte_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraarte',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
