# Generated by Django 4.2.5 on 2023-09-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGaleriaWeb', '0003_obraarte_vendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='artistas/'),
        ),
    ]
