# Generated by Django 4.2.5 on 2023-10-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGaleriaWeb', '0004_artista_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galerias/'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='obras',
            field=models.ManyToManyField(blank=True, related_name='galerias', to='AppGaleriaWeb.obraarte'),
        ),
    ]
