# Generated by Django 4.2.5 on 2023-10-07 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGaleriaWeb', '0005_galeria_imagen_alter_galeria_obras'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraarte',
            name='galeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppGaleriaWeb.galeria'),
        ),
    ]
